# Generated by Django 3.2.12 on 2022-06-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image_teacher', models.ImageField(upload_to='teacher')),
                ('about', models.TextField(max_length=300)),
            ],
        ),
    ]
