# Generated by Django 3.2.12 on 2022-03-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_contact', models.EmailField(max_length=30)),
                ('name', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=12)),
                ('subject', models.CharField(max_length=30)),
                ('message_contact', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Cooperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_contact', models.EmailField(max_length=30)),
                ('name', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=12)),
                ('cooperation_field', models.CharField(max_length=30)),
                ('message_contact', models.TextField(max_length=300)),
            ],
        ),
    ]
