# Generated by Django 3.2.12 on 2022-06-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cooperation',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email_contact',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message_contact',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
