# Generated by Django 3.2.12 on 2022-07-05 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_auto_20220626_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
