# Generated by Django 3.2.12 on 2022-03-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=100)),
                ('image_course', models.ImageField(upload_to='course')),
                ('videos', models.FileField(upload_to='course')),
                ('teacher', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
    ]
