# Generated by Django 3.2.12 on 2022-03-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
