# Generated by Django 3.2.12 on 2022-03-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='length',
            field=models.IntegerField(blank=True),
        ),
    ]
