# Generated by Django 3.2.12 on 2022-07-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20220705_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcourse',
            name='course_ptr',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='SubCourse',
        ),
    ]
