# Generated by Django 3.2.12 on 2022-07-06 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_auto_20220706_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=50)),
                ('image_course', models.ImageField(upload_to='course')),
                ('teacher', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=300)),
                ('length', models.CharField(max_length=15)),
                ('course_type', models.CharField(choices=[('video', 'video'), ('booklet', 'booklet')], default='booklet', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SubCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_videos', models.FileField(upload_to='course')),
                ('sub_name', models.CharField(max_length=20)),
                ('sub_image_course', models.ImageField(upload_to='course')),
                ('sub_context', models.TextField(max_length=9000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
