# Generated by Django 3.2.12 on 2022-07-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_subcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='length',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subcourse',
            name='sub_context',
            field=models.TextField(max_length=9000, null=True),
        ),
        migrations.AlterField(
            model_name='subcourse',
            name='sub_image_course',
            field=models.ImageField(null=True, upload_to='course'),
        ),
        migrations.AlterField(
            model_name='subcourse',
            name='sub_videos',
            field=models.FileField(null=True, upload_to='course'),
        ),
    ]
