# Generated by Django 3.2.12 on 2022-07-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20220706_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcourse',
            name='sub_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subcourse',
            name='sub_videos',
            field=models.FileField(blank=True, null=True, upload_to='course'),
        ),
    ]
